//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiProc
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlternativeCapex1
    {
        public int AltCapexID { get; set; }
        public Nullable<int> DId { get; set; }
        public Nullable<int> AltCapexItemID { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<int> FinYrID { get; set; }
        public Nullable<System.DateTime> dte { get; set; }
    }
}
