
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DigiProc
{

using System;
    using System.Collections.Generic;
    
public partial class Capex
{

    public int CapexID { get; set; }

    public Nullable<int> CapexTypeID { get; set; }

    public string EstimatedDeadline { get; set; }

    public Nullable<int> QuantityRequested { get; set; }

    public Nullable<int> QuantitySupplied { get; set; }

    public Nullable<int> QuantityOutstanding { get; set; }

    public string Justification { get; set; }

    public Nullable<int> FinancialYrId { get; set; }

    public Nullable<int> DId { get; set; }

    public Nullable<int> CapexItemID { get; set; }

}

}
