
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DigiProc
{

using System;
    using System.Collections.Generic;
    
public partial class FinancialYear
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public FinancialYear()
    {

        this.Requisitions = new HashSet<Requisition>();

    }


    public int FinancialYrID { get; set; }

    public string FinancialYr { get; set; }

    public string Description { get; set; }

    public Nullable<int> IsActive { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Requisition> Requisitions { get; set; }

}

}
