//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiProc
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logger
    {
        public int LogID { get; set; }
        public string LogEntity { get; set; }
        public string LogEvent { get; set; }
        public string LogDescription { get; set; }
        public string LogActor { get; set; }
    }
}
