//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiProc
{
    using System;
    using System.Collections.Generic;
    
    public partial class LPO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LPO()
        {
            this.RequisitionItems = new HashSet<RequisitionItem>();
        }
    
        public int LPOID { get; set; }
        public string RequisitionNo { get; set; }
        public Nullable<decimal> VAT { get; set; }
        public Nullable<System.DateTime> PurchaseOrderDate { get; set; }
        public Nullable<System.DateTime> ExpectedDeliveryDate { get; set; }
        public string ShippingAddress { get; set; }
        public string PaymentTerm { get; set; }
        public string OtherTermsAndConditions { get; set; }
        public Nullable<int> LPOStatusID { get; set; }
        public Nullable<int> VendorID { get; set; }
        public Nullable<decimal> TotAmt { get; set; }
        public string LPONo { get; set; }
        public Nullable<decimal> NetAmt { get; set; }
        public Nullable<int> ProcurementTypeId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequisitionItem> RequisitionItems { get; set; }
    }
}
