
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DigiProc
{

using System;
    using System.Collections.Generic;
    
public partial class ProcessFlow
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ProcessFlow()
    {

        this.PFNotificationLists = new HashSet<PFNotificationList>();

    }


    public int ProcessFlowID { get; set; }

    public Nullable<int> ProcurementTypeId { get; set; }

    public Nullable<decimal> Limit { get; set; }

    public Nullable<int> ProcessFlowOrder { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PFNotificationList> PFNotificationLists { get; set; }

    public virtual ProcurementType ProcurementType { get; set; }

}

}
