//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiProc
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequisitionFile1
    {
        public int RequisitionFileID { get; set; }
        public Nullable<int> RequisitionID { get; set; }
        public string RequisitionFileDescription { get; set; }
        public byte[] RequisitionFileName { get; set; }
    }
}
