//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiProc
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vendor()
        {
            this.Requisitions = new HashSet<Requisition>();
        }
    
        public int VendorID { get; set; }
        public string VendorName { get; set; }
        public string ContactPerson { get; set; }
        public Nullable<int> VendorTypeID { get; set; }
        public string CompanyRegistrationNo { get; set; }
        public Nullable<System.DateTime> IncorporationDate { get; set; }
        public string TIN { get; set; }
        public string NameOfOwner { get; set; }
        public string CompanyContact { get; set; }
        public string CompanyWebsite { get; set; }
        public string CompanyEmailAddress { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public string VendorNo { get; set; }
        public string VendorLocation { get; set; }
        public string CompanyFb { get; set; }
        public string CompanyLinkedIn { get; set; }
        public string CompanyGHPostAddress { get; set; }
        public string CompanyHomeContact { get; set; }
        public Nullable<int> CompanyBusinessTypeID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Requisition> Requisitions { get; set; }
        public virtual VendorType VendorType { get; set; }
        public virtual BusinessType BusinessType { get; set; }
    }
}
