//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiProc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Committee
    {
        public int CommitteeID { get; set; }
        public string CommitteeName { get; set; }
        public string CommitteeDescription { get; set; }
    }
}
