//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiProc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequisitionType
    {
        public int RequisitionID { get; set; }
        public string RequisitionType1 { get; set; }
        public string RequisitionDescription { get; set; }
    }
}
