//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiProc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserModule
    {
        public int UserModuleID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string SystemName { get; set; }
        public string PublicName { get; set; }
        public Nullable<System.DateTime> DateAssigned { get; set; }
    }
}
