//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiProc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendor
    {
        public int VendorID { get; set; }
        public string VendorName { get; set; }
        public string ContactPerson { get; set; }
        public Nullable<int> VendorTypeID { get; set; }
        public string CompanyRegistrationNo { get; set; }
        public Nullable<System.DateTime> IncorporationDate { get; set; }
        public string NameOfOwner { get; set; }
        public string CompanyContact { get; set; }
        public string CompanyWebsite { get; set; }
        public string CompanyEmailAddress { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
    }
}
